AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam test
Globals:
  Function:
    Timeout: 3
    Tracing: Active

Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64


